GET http://localhost:3003

###
POST http://localhost:3003/student/create
Content-Type: application/json

{
    "name":"Ju",
    "email":"juliene@gmail.com",
    "birthdate":"2000-04-15",
    "hobbies": "Dormir."
}

####
POST http://localhost:3003/class/create
Content-Type: application/json

{
    "name":"Turma Ana da Hora",
    "start_date":"2021-07-01",
    "end_date":"2022-01-01",
    "type_class": "Integral"
}

###
POST http://localhost:3003/teacher/create
Content-Type: application/json

{
    "name":"Caio",
    "email":"caio@gmail.com",
    "birthdate":"1990-04-15",
    "speciality": "Redux"
}

### 
PUT http://localhost:3003/update/class
Content-Type: application/json

{
    "tableName": "Teachers",
    "peapleClassId": "1617296352730",
    "peapleNewClassId": "1617299457911"
}